# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Carga_electronica.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Elementos_propios import BotonIluminado


class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        dpi = MainWindow.screen().physicalDotsPerInch()
        w = int(8.27 * dpi)
        h = int(4.47 * dpi)
        #MainWindow.resize(930, 503)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(w, h))
        MainWindow.setMaximumSize(QtCore.QSize(w, h))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(255, 245, 226);")
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        MainWindow.resize(w, h)
        MainWindow.adjustSize()
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(10, 120, 911, 364))
        tam=self.tabWidget.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.tabWidget.setGeometry(QtCore.QRect(*esc))        
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(10, 20, 436, 68))
        tam=self.frame.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 47, 22))
        tam=self.label_2.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_2.setGeometry(QtCore.QRect(*esc))
        self.label_2.setObjectName("label_2")
        self.CmbPuerto = QtWidgets.QComboBox(self.frame)
        self.CmbPuerto.setGeometry(QtCore.QRect(80, 30, 69, 22))
        tam=self.CmbPuerto.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.CmbPuerto.setGeometry(QtCore.QRect(*esc))
        radio = 4 / 112.5222328226425 * dpi
        borde = 1 / 112.5222328226425 * dpi
        self.CmbPuerto.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.CmbPuerto.setEditable(False)
        self.CmbPuerto.setCurrentText("")
        self.CmbPuerto.setObjectName("CmbPuerto")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(180, 30, 47, 22))
        tam=self.label_3.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_3.setGeometry(QtCore.QRect(*esc))
        self.label_3.setObjectName("label_3")
        self.CmbBaudrate = QtWidgets.QComboBox(self.frame)
        self.CmbBaudrate.setGeometry(QtCore.QRect(230, 30, 69, 22))
        tam=self.CmbBaudrate.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.CmbBaudrate.setGeometry(QtCore.QRect(*esc))
        radio = 4 / 112.5222328226425 * dpi
        borde = 1 / 112.5222328226425 * dpi
        self.CmbBaudrate.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.CmbBaudrate.setObjectName("CmbBaudrate")
        self.CmbBaudrate.addItem("")
        self.CmbBaudrate.addItem("")
        self.CmbBaudrate.addItem("")
        self.CmbBaudrate.addItem("")
        self.BtnConectar = BotonIluminado(self.frame)
        self.BtnConectar.setGeometry(QtCore.QRect(330, 28, 75, 26))
        tam=self.BtnConectar.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnConectar.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnConectar.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnConectar.setObjectName("BtnConectar")
        self.BtnDesconectar = BotonIluminado(self.frame)
        self.BtnDesconectar.setGeometry(QtCore.QRect(330, 28, 75, 26))
        tam=self.BtnDesconectar.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnDesconectar.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnDesconectar.setStyleSheet("color: black;\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;\n"
"background-color: rgb(251, 252, 252);")
        self.BtnDesconectar.setObjectName("BtnDesconectar")
        self.BtnDesconectar.raise_()
        self.BtnConectar.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.CmbPuerto.raise_()
        self.label_3.raise_()
        self.CmbBaudrate.raise_()
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(10, 104, 436, 95))
        tam=self.frame_3.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_3.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_3.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_10.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_10.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 96, 22))
        tam=self.label_11.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_11.setGeometry(QtCore.QRect(*esc))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_3)
        self.label_12.setGeometry(QtCore.QRect(230, 30, 96, 22))
        tam=self.label_12.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_12.setGeometry(QtCore.QRect(*esc))
        self.label_12.setObjectName("label_12")
        self.BtnEstablecerMax = BotonIluminado(self.frame_3)
        self.BtnEstablecerMax.setGeometry(QtCore.QRect(318, 58, 75, 26))
        tam=self.BtnEstablecerMax.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnEstablecerMax.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnEstablecerMax.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnEstablecerMax.setObjectName("BtnEstablecerMax")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 60, 95, 22))
        tam=self.label_13.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_13.setGeometry(QtCore.QRect(*esc))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(180, 30, 21, 22))
        tam=self.label_14.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_14.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(390, 30, 21, 22))
        tam=self.label_15.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_15.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(180, 60, 21, 22))
        tam=self.label_16.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_16.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.TextLimV = QtWidgets.QLineEdit(self.frame_3)
        self.TextLimV.setGeometry(QtCore.QRect(116, 28, 60, 26))
        tam=self.TextLimV.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextLimV.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextLimV.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.TextLimV.setInputMethodHints(QtCore.Qt.ImhNone)
        self.TextLimV.setInputMask("")
        self.TextLimV.setText("")
        self.TextLimV.setMaxLength(8)
        self.TextLimV.setObjectName("TextLimV")
        self.TextLimP = QtWidgets.QLineEdit(self.frame_3)
        self.TextLimP.setGeometry(QtCore.QRect(116, 58, 60, 26))
        tam=self.TextLimP.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextLimP.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextLimP.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.TextLimP.setMaxLength(8)
        self.TextLimP.setObjectName("TextLimP")
        self.TextLimC = QtWidgets.QLineEdit(self.frame_3)
        self.TextLimC.setGeometry(QtCore.QRect(326, 28, 60, 26))
        tam=self.TextLimC.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextLimC.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextLimC.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.TextLimC.setMaxLength(8)
        self.TextLimC.setObjectName("TextLimC")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(10, 215, 436, 115))
        tam=self.frame_2.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_2.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_2.setStyleSheet("background-color:rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_4.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_4.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(216, 35, 140, 22))
        tam=self.label_6.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_6.setGeometry(QtCore.QRect(*esc))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(80, 35, 50, 22))
        tam=self.label_5.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_5.setGeometry(QtCore.QRect(*esc))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.LblModelo = QtWidgets.QLabel(self.frame_2)
        self.LblModelo.setGeometry(QtCore.QRect(80, 70, 50, 22))
        tam=self.LblModelo.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblModelo.setGeometry(QtCore.QRect(*esc))
        self.LblModelo.setText("")
        self.LblModelo.setScaledContents(True)
        self.LblModelo.setAlignment(QtCore.Qt.AlignCenter)
        self.LblModelo.setObjectName("LblModelo")
        self.LblRangoP = QtWidgets.QLabel(self.frame_2)
        self.LblRangoP.setGeometry(QtCore.QRect(210, 70, 28, 22))
        tam=self.LblRangoP.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblRangoP.setGeometry(QtCore.QRect(*esc))
        self.LblRangoP.setText("")
        self.LblRangoP.setScaledContents(True)
        self.LblRangoP.setAlignment(QtCore.Qt.AlignCenter)
        self.LblRangoP.setObjectName("LblRangoP")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(238, 70, 21, 22))
        tam=self.label_17.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_17.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.LblRangoV = QtWidgets.QLabel(self.frame_2)
        self.LblRangoV.setGeometry(QtCore.QRect(264, 70, 24, 22))
        tam=self.LblRangoV.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblRangoV.setGeometry(QtCore.QRect(*esc))
        self.LblRangoV.setText("")
        self.LblRangoV.setScaledContents(True)
        self.LblRangoV.setAlignment(QtCore.Qt.AlignCenter)
        self.LblRangoV.setObjectName("LblRangoV")
        self.label_18 = QtWidgets.QLabel(self.frame_2)
        self.label_18.setGeometry(QtCore.QRect(288, 70, 21, 22))
        tam=self.label_18.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_18.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.LblRangoC = QtWidgets.QLabel(self.frame_2)
        self.LblRangoC.setGeometry(QtCore.QRect(316, 70, 28, 22))
        tam=self.LblRangoC.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblRangoC.setGeometry(QtCore.QRect(*esc))
        self.LblRangoC.setText("")
        self.LblRangoC.setScaledContents(True)
        self.LblRangoC.setAlignment(QtCore.Qt.AlignCenter)
        self.LblRangoC.setObjectName("LblRangoC")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(344, 70, 21, 22))
        tam=self.label_19.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_19.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(460, 104, 436, 95))
        tam=self.frame_5.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_5.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_5.setStyleSheet("background-color: rgb(255, 231, 215);\n"
        f"border-radius: {radio}px;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_35 = QtWidgets.QLabel(self.frame_5)
        self.label_35.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_35.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_35.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.Rbtn_MCC = QtWidgets.QRadioButton(self.frame_5)
        self.Rbtn_MCC.setGeometry(QtCore.QRect(48, 60, 40, 17))
        tam=self.Rbtn_MCC.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_MCC.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_MCC.setObjectName("Rbtn_MCC")
        self.Rbtn_MCV = QtWidgets.QRadioButton(self.frame_5)
        self.Rbtn_MCV.setGeometry(QtCore.QRect(148, 60, 40, 17))
        tam=self.Rbtn_MCV.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_MCV.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_MCV.setObjectName("Rbtn_MCV")
        self.Rbtn_MCW = QtWidgets.QRadioButton(self.frame_5)
        self.Rbtn_MCW.setGeometry(QtCore.QRect(248, 60, 40, 17))
        tam=self.Rbtn_MCW.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_MCW.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_MCW.setObjectName("Rbtn_MCW")
        self.Rbtn_MCR = QtWidgets.QRadioButton(self.frame_5)
        self.Rbtn_MCR.setGeometry(QtCore.QRect(348, 60, 40, 17))
        tam=self.Rbtn_MCR.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_MCR.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_MCR.setObjectName("Rbtn_MCR")
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        self.label_9.setGeometry(QtCore.QRect(0, 27, 436, 22))
        tam=self.label_9.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_9.setGeometry(QtCore.QRect(*esc))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.frame_6 = QtWidgets.QFrame(self.tab)
        self.frame_6.setGeometry(QtCore.QRect(460, 215, 436, 115))
        tam=self.frame_6.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_6.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_6.setStyleSheet("background-color:rgb(255, 231, 215);\n"
        f"border-radius: {radio}px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_36 = QtWidgets.QLabel(self.frame_6)
        self.label_36.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_36.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_36.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.frame_6)
        self.label_37.setGeometry(QtCore.QRect(35, 26, 82, 22))
        tam=self.label_37.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_37.setGeometry(QtCore.QRect(*esc))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.frame_6)
        self.label_38.setGeometry(QtCore.QRect(230, 26, 82, 22))
        tam=self.label_38.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_38.setGeometry(QtCore.QRect(*esc))
        self.label_38.setObjectName("label_38")
        self.BtnEstablecerValMod = BotonIluminado(self.frame_6)
        self.BtnEstablecerValMod.setGeometry(QtCore.QRect(180, 82, 75, 26))
        tam=self.BtnEstablecerValMod.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnEstablecerValMod.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnEstablecerValMod.setStyleSheet("color: black;\n"
        "background-color: rgb(251, 252, 252);\n"
        f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "border-style: outset;")
        self.BtnEstablecerValMod.setObjectName("BtnEstablecerValMod")
        self.label_39 = QtWidgets.QLabel(self.frame_6)
        self.label_39.setGeometry(QtCore.QRect(35, 56, 82, 22))
        tam=self.label_39.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_39.setGeometry(QtCore.QRect(*esc))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.frame_6)
        self.label_40.setGeometry(QtCore.QRect(175, 26, 21, 22))
        tam=self.label_40.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_40.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.frame_6)
        self.label_41.setGeometry(QtCore.QRect(380, 26, 21, 22))
        tam=self.label_41.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_41.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.frame_6)
        self.label_42.setGeometry(QtCore.QRect(175, 56, 21, 22))
        tam=self.label_42.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_42.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.frame_6)
        self.label_43.setGeometry(QtCore.QRect(380, 56, 21, 22))
        tam=self.label_43.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_43.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.frame_6)
        self.label_44.setGeometry(QtCore.QRect(230, 56, 82, 22))
        tam=self.label_44.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_44.setGeometry(QtCore.QRect(*esc))
        self.label_44.setObjectName("label_44")
        self.TextVCV = QtWidgets.QLineEdit(self.frame_6)
        self.TextVCV.setGeometry(QtCore.QRect(117, 24, 60, 26))
        tam=self.TextVCV.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextVCV.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextVCV.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "background-color: rgb(251, 252, 252);")
        self.TextVCV.setMaxLength(9)
        self.TextVCV.setObjectName("TextVCV")
        self.TextCCC = QtWidgets.QLineEdit(self.frame_6)
        self.TextCCC.setGeometry(QtCore.QRect(320, 24, 60, 26))
        tam=self.TextCCC.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextCCC.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextCCC.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "background-color: rgb(251, 252, 252);")
        self.TextCCC.setMaxLength(9)
        self.TextCCC.setObjectName("TextCCC")
        self.TextPCW = QtWidgets.QLineEdit(self.frame_6)
        self.TextPCW.setGeometry(QtCore.QRect(117, 54, 60, 26))
        tam=self.TextPCW.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextPCW.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextPCW.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "background-color: rgb(251, 252, 252);")
        self.TextPCW.setMaxLength(9)
        self.TextPCW.setObjectName("TextPCW")
        self.TextRCR = QtWidgets.QLineEdit(self.frame_6)
        self.TextRCR.setGeometry(QtCore.QRect(320, 54, 60, 26))
        tam=self.TextRCR.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextRCR.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextRCR.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "background-color: rgb(251, 252, 252);")
        self.TextRCR.setMaxLength(9)
        self.TextRCR.setObjectName("TextRCR")
        self.frame_4 = QtWidgets.QFrame(self.tab)
        self.frame_4.setGeometry(QtCore.QRect(460, 20, 436, 68))
        tam=self.frame_4.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_4.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_4.setStyleSheet("background-color: rgb(255, 231, 215);\n"
        f"border-radius: {radio}px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_34 = QtWidgets.QLabel(self.frame_4)
        self.label_34.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_34.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_34.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.BtnApagar = BotonIluminado(self.frame_4)
        self.BtnApagar.setGeometry(QtCore.QRect(181, 30, 75, 26))
        tam=self.BtnApagar.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnApagar.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnApagar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.BtnApagar.setStyleSheet("color: black;\n"
        "background-color: rgb(251, 252, 252);\n"
        f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "border-style: outset;")
        self.BtnApagar.setObjectName("BtnApagar")
        self.BtnEncender = BotonIluminado(self.frame_4)
        self.BtnEncender.setGeometry(QtCore.QRect(181, 30, 75, 26))
        tam=self.BtnEncender.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnEncender.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnEncender.setStyleSheet("color: black;\n"
        "background-color: rgb(251, 252, 252);\n"
        f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "border-style: outset;")
        self.BtnEncender.setObjectName("BtnEncender")
        self.BtnApagar.raise_()
        self.BtnEncender.raise_()
        self.label_34.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.frame_10 = QtWidgets.QFrame(self.tab_3)
        self.frame_10.setGeometry(QtCore.QRect(460, 80, 436, 251))
        tam=self.frame_10.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_10.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_10.setStyleSheet("background-color: rgb(255, 231, 215);\n"
        f"border-radius: {radio}px;")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_54 = QtWidgets.QLabel(self.frame_10)
        self.label_54.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_54.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_54.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.label_58 = QtWidgets.QLabel(self.frame_10)
        self.label_58.setGeometry(QtCore.QRect(49, 110, 60, 22))
        tam=self.label_58.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_58.setGeometry(QtCore.QRect(*esc))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.frame_10)
        self.label_59.setGeometry(QtCore.QRect(49, 150, 60, 22))
        tam=self.label_59.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_59.setGeometry(QtCore.QRect(*esc))
        self.label_59.setObjectName("label_59")
        self.label_61 = QtWidgets.QLabel(self.frame_10)
        self.label_61.setGeometry(QtCore.QRect(267, 150, 60, 22))
        tam=self.label_61.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_61.setGeometry(QtCore.QRect(*esc))
        self.label_61.setObjectName("label_61")
        self.BtnEstablecer_OpLista = BotonIluminado(self.frame_10)
        self.BtnEstablecer_OpLista.setGeometry(QtCore.QRect(220, 200, 75, 26))
        tam=self.BtnEstablecer_OpLista.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnEstablecer_OpLista.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnEstablecer_OpLista.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnEstablecer_OpLista.setObjectName("BtnEstablecer_OpLista")
        self.label_49 = QtWidgets.QLabel(self.frame_10)
        self.label_49.setGeometry(QtCore.QRect(170, 70, 31, 22))
        tam=self.label_49.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_49.setGeometry(QtCore.QRect(*esc))
        self.label_49.setObjectName("label_49")
        self.Cmb_ModoLista = QtWidgets.QComboBox(self.frame_10)
        self.Cmb_ModoLista.setGeometry(QtCore.QRect(200, 70, 69, 22))
        tam=self.Cmb_ModoLista.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Cmb_ModoLista.setGeometry(QtCore.QRect(*esc))
        radio = 4 / 112.5222328226425 * dpi
        borde = 1 / 112.5222328226425 * dpi
        self.Cmb_ModoLista.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border:{borde}px groove gray;\n"
"border-style: outset;")
        self.Cmb_ModoLista.setEditable(False)
        self.Cmb_ModoLista.setObjectName("Cmb_ModoLista")
        self.Cmb_ModoLista.addItem("")
        self.Cmb_ModoLista.addItem("")
        self.Cmb_ModoLista.addItem("")
        self.Cmb_ModoLista.addItem("")
        self.label_51 = QtWidgets.QLabel(self.frame_10)
        self.label_51.setGeometry(QtCore.QRect(267, 110, 60, 22))
        tam=self.label_51.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_51.setGeometry(QtCore.QRect(*esc))
        self.label_51.setObjectName("label_51")
        self.frame_8 = QtWidgets.QFrame(self.frame_10)
        self.frame_8.setGeometry(QtCore.QRect(50, 197, 141, 32))
        tam=self.frame_8.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_8.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_8.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.Rbtn_Unavez = QtWidgets.QRadioButton(self.frame_8)
        self.Rbtn_Unavez.setGeometry(QtCore.QRect(10, 7, 61, 18))
        tam=self.Rbtn_Unavez.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Unavez.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Unavez.setObjectName("Rbtn_Unavez")
        self.Rbtn_Repetir = QtWidgets.QRadioButton(self.frame_8)
        self.Rbtn_Repetir.setGeometry(QtCore.QRect(80, 7, 61, 18))
        tam=self.Rbtn_Repetir.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Repetir.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Repetir.setObjectName("Rbtn_Repetir")
        self.label_56 = QtWidgets.QLabel(self.frame_10)
        self.label_56.setGeometry(QtCore.QRect(40, 20, 356, 40))
        tam=self.label_56.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_56.setGeometry(QtCore.QRect(*esc))
        self.label_56.setScaledContents(False)
        self.label_56.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.label_56.setWordWrap(True)
        self.label_56.setObjectName("label_56")
        self.BtnIniciar_Lista = BotonIluminado(self.frame_10)
        self.BtnIniciar_Lista.setGeometry(QtCore.QRect(320, 200, 75, 26))
        tam=self.BtnIniciar_Lista.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnIniciar_Lista.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnIniciar_Lista.setStyleSheet("color: black;\n"
        "background-color: rgb(251, 252, 252);\n"
        f"border-radius: {radio}px; border: {borde}px groove gray;\n"
        "border-style: outset;")
        self.BtnIniciar_Lista.setObjectName("BtnIniciar_Lista")
        self.BtnParar_Lista = BotonIluminado(self.frame_10)
        self.BtnParar_Lista.setGeometry(QtCore.QRect(320, 200, 75, 26))
        tam=self.BtnParar_Lista.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnParar_Lista.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnParar_Lista.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnParar_Lista.setObjectName("BtnParar_Lista")
        self.Txt_Val_min = QtWidgets.QLineEdit(self.frame_10)
        self.Txt_Val_min.setGeometry(QtCore.QRect(109, 108, 60, 26))
        tam=self.Txt_Val_min.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_Val_min.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_Val_min.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.Txt_Val_min.setMaxLength(9)
        self.Txt_Val_min.setObjectName("Txt_Val_min")
        self.Txt_NumPasos = QtWidgets.QLineEdit(self.frame_10)
        self.Txt_NumPasos.setGeometry(QtCore.QRect(327, 108, 60, 26))
        tam=self.Txt_NumPasos.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_NumPasos.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_NumPasos.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.Txt_NumPasos.setMaxLength(9)
        self.Txt_NumPasos.setObjectName("Txt_NumPasos")
        self.Txt_Val_max = QtWidgets.QLineEdit(self.frame_10)
        self.Txt_Val_max.setGeometry(QtCore.QRect(109, 148, 60, 26))
        tam=self.Txt_Val_max.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_Val_max.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_Val_max.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.Txt_Val_max.setMaxLength(9)
        self.Txt_Val_max.setObjectName("Txt_Val_max")
        self.Txt_Val_tiempo = QtWidgets.QLineEdit(self.frame_10)
        self.Txt_Val_tiempo.setGeometry(QtCore.QRect(327, 148, 60, 26))
        tam=self.Txt_Val_tiempo.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_Val_tiempo.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_Val_tiempo.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.Txt_Val_tiempo.setMaxLength(9)
        self.Txt_Val_tiempo.setObjectName("Txt_Val_tiempo")
        self.LblPotmin = QtWidgets.QLabel(self.frame_10)
        self.LblPotmin.setGeometry(QtCore.QRect(169, 110, 21, 22))
        tam=self.LblPotmin.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblPotmin.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblPotmin.setFont(font)
        self.LblPotmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LblPotmin.setObjectName("LblPotmin")
        self.LblVmin = QtWidgets.QLabel(self.frame_10)
        self.LblVmin.setGeometry(QtCore.QRect(169, 110, 21, 22))
        tam=self.LblVmin.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblVmin.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblVmin.setFont(font)
        self.LblVmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LblVmin.setObjectName("LblVmin")
        self.LblOhmmax = QtWidgets.QLabel(self.frame_10)
        self.LblOhmmax.setGeometry(QtCore.QRect(169, 150, 21, 22))
        tam=self.LblOhmmax.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblOhmmax.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblOhmmax.setFont(font)
        self.LblOhmmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LblOhmmax.setObjectName("LblOhmmax")
        self.LblVmax = QtWidgets.QLabel(self.frame_10)
        self.LblVmax.setGeometry(QtCore.QRect(169, 150, 21, 22))
        tam=self.LblVmax.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblVmax.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblVmax.setFont(font)
        self.LblVmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LblVmax.setObjectName("LblVmax")
        self.label_68 = QtWidgets.QLabel(self.frame_10)
        self.label_68.setGeometry(QtCore.QRect(387, 150, 21, 22))
        tam=self.label_68.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_68.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_68.setFont(font)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.LblCmin = QtWidgets.QLabel(self.frame_10)
        self.LblCmin.setEnabled(True)
        self.LblCmin.setGeometry(QtCore.QRect(169, 110, 21, 22))
        tam=self.LblCmin.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblCmin.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblCmin.setFont(font)
        self.LblCmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LblCmin.setObjectName("LblCmin")
        self.LblCmax = QtWidgets.QLabel(self.frame_10)
        self.LblCmax.setGeometry(QtCore.QRect(169, 150, 21, 22))
        tam=self.LblCmax.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblCmax.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblCmax.setFont(font)
        self.LblCmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LblCmax.setObjectName("LblCmax")
        self.LblPotmax = QtWidgets.QLabel(self.frame_10)
        self.LblPotmax.setGeometry(QtCore.QRect(169, 150, 21, 22))
        tam=self.LblPotmax.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblPotmax.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblPotmax.setFont(font)
        self.LblPotmax.setAlignment(QtCore.Qt.AlignCenter)
        self.LblPotmax.setObjectName("LblPotmax")
        self.LblOhmmin = QtWidgets.QLabel(self.frame_10)
        self.LblOhmmin.setGeometry(QtCore.QRect(169, 110, 21, 22))
        tam=self.LblOhmmin.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblOhmmin.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.LblOhmmin.setFont(font)
        self.LblOhmmin.setAlignment(QtCore.Qt.AlignCenter)
        self.LblOhmmin.setObjectName("LblOhmmin")
        self.BtnParar_Lista.raise_()
        self.LblPotmax.raise_()
        self.LblOhmmax.raise_()
        self.LblVmax.raise_()
        self.LblCmax.raise_()
        self.LblPotmin.raise_()
        self.LblOhmmin.raise_()
        self.LblVmin.raise_()
        self.LblCmin.raise_()
        self.BtnIniciar_Lista.raise_()
        self.label_54.raise_()
        self.label_58.raise_()
        self.label_59.raise_()
        self.label_61.raise_()
        self.BtnEstablecer_OpLista.raise_()
        self.label_49.raise_()
        self.Cmb_ModoLista.raise_()
        self.label_51.raise_()
        self.frame_8.raise_()
        self.label_56.raise_()
        self.Txt_Val_min.raise_()
        self.Txt_NumPasos.raise_()
        self.Txt_Val_max.raise_()
        self.Txt_Val_tiempo.raise_()
        self.label_68.raise_()
        self.Lbl_Ah = QtWidgets.QLabel(self.tab_3)
        self.Lbl_Ah.setGeometry(QtCore.QRect(200, 50, 47, 13))
        tam=self.Lbl_Ah.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Lbl_Ah.setGeometry(QtCore.QRect(*esc))
        self.Lbl_Ah.setText("")
        self.Lbl_Ah.setObjectName("Lbl_Ah")
        self.Lbl_Wh = QtWidgets.QLabel(self.tab_3)
        self.Lbl_Wh.setGeometry(QtCore.QRect(200, 90, 47, 13))
        tam=self.Lbl_Wh.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Lbl_Wh.setGeometry(QtCore.QRect(*esc))
        self.Lbl_Wh.setText("")
        self.Lbl_Wh.setObjectName("Lbl_Wh")
        self.frame_7 = QtWidgets.QFrame(self.tab_3)
        self.frame_7.setGeometry(QtCore.QRect(10, 90, 436, 101))
        tam=self.frame_7.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_7.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_7.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.BtnParar_PBateria = BotonIluminado(self.frame_7)
        self.BtnParar_PBateria.setGeometry(QtCore.QRect(340, 40, 75, 26))
        tam=self.BtnParar_PBateria.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnParar_PBateria.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnParar_PBateria.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnParar_PBateria.setObjectName("BtnParar_PBateria")
        self.label_46 = QtWidgets.QLabel(self.frame_7)
        self.label_46.setGeometry(QtCore.QRect(20, 60, 70, 22))
        tam=self.label_46.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_46.setGeometry(QtCore.QRect(*esc))
        self.label_46.setObjectName("label_46")
        self.BtnIniciar_PBateria = BotonIluminado(self.frame_7)
        self.BtnIniciar_PBateria.setGeometry(QtCore.QRect(340, 40, 75, 26))
        tam=self.BtnIniciar_PBateria.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnIniciar_PBateria.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnIniciar_PBateria.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnIniciar_PBateria.setObjectName("BtnIniciar_PBateria")
        self.label_45 = QtWidgets.QLabel(self.frame_7)
        self.label_45.setGeometry(QtCore.QRect(20, 30, 70, 22))
        tam=self.label_45.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_45.setGeometry(QtCore.QRect(*esc))
        self.label_45.setObjectName("label_45")
        self.label_55 = QtWidgets.QLabel(self.frame_7)
        self.label_55.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_55.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_55.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.label_47 = QtWidgets.QLabel(self.frame_7)
        self.label_47.setGeometry(QtCore.QRect(180, 45, 61, 22))
        tam=self.label_47.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_47.setGeometry(QtCore.QRect(*esc))
        self.label_47.setObjectName("label_47")
        self.Lbl_CapAh = QtWidgets.QLabel(self.frame_7)
        self.Lbl_CapAh.setGeometry(QtCore.QRect(250, 30, 50, 22))
        tam=self.Lbl_CapAh.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Lbl_CapAh.setGeometry(QtCore.QRect(*esc))
        self.Lbl_CapAh.setText("")
        self.Lbl_CapAh.setObjectName("Lbl_CapAh")
        self.Lbl_CapWh = QtWidgets.QLabel(self.frame_7)
        self.Lbl_CapWh.setGeometry(QtCore.QRect(250, 60, 50, 22))
        tam=self.Lbl_CapWh.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Lbl_CapWh.setGeometry(QtCore.QRect(*esc))
        self.Lbl_CapWh.setText("")
        self.Lbl_CapWh.setObjectName("Lbl_CapWh")
        self.TextCCC_Bat = QtWidgets.QLineEdit(self.frame_7)
        self.TextCCC_Bat.setGeometry(QtCore.QRect(90, 28, 60, 26))
        tam=self.TextCCC_Bat.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextCCC_Bat.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextCCC_Bat.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.TextCCC_Bat.setMaxLength(9)
        self.TextCCC_Bat.setObjectName("TextCCC_Bat")
        self.TextVoltmin_PBateria = QtWidgets.QLineEdit(self.frame_7)
        self.TextVoltmin_PBateria.setGeometry(QtCore.QRect(90, 58, 60, 26))
        tam=self.TextVoltmin_PBateria.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.TextVoltmin_PBateria.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.TextVoltmin_PBateria.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);")
        self.TextVoltmin_PBateria.setMaxLength(9)
        self.TextVoltmin_PBateria.setObjectName("TextVoltmin_PBateria")
        self.label_62 = QtWidgets.QLabel(self.frame_7)
        self.label_62.setGeometry(QtCore.QRect(300, 30, 21, 22))
        tam=self.label_62.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_62.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.frame_7)
        self.label_63.setGeometry(QtCore.QRect(300, 60, 21, 22))
        tam=self.label_63.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_63.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.BtnParar_PBateria.raise_()
        self.BtnIniciar_PBateria.raise_()
        self.label_46.raise_()
        self.label_45.raise_()
        self.label_55.raise_()
        self.label_47.raise_()
        self.Lbl_CapAh.raise_()
        self.Lbl_CapWh.raise_()
        self.TextCCC_Bat.raise_()
        self.TextVoltmin_PBateria.raise_()
        self.label_62.raise_()
        self.label_63.raise_()
        self.frame_9 = QtWidgets.QFrame(self.tab_3)
        self.frame_9.setGeometry(QtCore.QRect(10, 16, 886, 51))
        tam=self.frame_9.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_9.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_9.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_50 = QtWidgets.QLabel(self.frame_9)
        self.label_50.setGeometry(QtCore.QRect(0, 0, 886, 20))
        tam=self.label_50.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_50.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_50.setFont(font)
        self.label_50.setAlignment(QtCore.Qt.AlignCenter)
        self.label_50.setObjectName("label_50")
        self.Rbtn_Fijo = QtWidgets.QRadioButton(self.frame_9)
        self.Rbtn_Fijo.setEnabled(False)
        self.Rbtn_Fijo.setGeometry(QtCore.QRect(250, 10, 40, 17))
        tam=self.Rbtn_Fijo.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Fijo.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Fijo.setObjectName("Rbtn_Fijo")
        self.Rbtn_Corto = QtWidgets.QRadioButton(self.frame_9)
        self.Rbtn_Corto.setGeometry(QtCore.QRect(50, 25, 121, 17))
        tam=self.Rbtn_Corto.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Corto.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Corto.setObjectName("Rbtn_Corto")
        self.Rbtn_Lista = QtWidgets.QRadioButton(self.frame_9)
        self.Rbtn_Lista.setGeometry(QtCore.QRect(418, 25, 51, 17))
        tam=self.Rbtn_Lista.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Lista.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Lista.setObjectName("Rbtn_Lista")
        self.Rbtn_Bateria = QtWidgets.QRadioButton(self.frame_9)
        self.Rbtn_Bateria.setGeometry(QtCore.QRect(720, 25, 111, 17))
        tam=self.Rbtn_Bateria.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Rbtn_Bateria.setGeometry(QtCore.QRect(*esc))
        self.Rbtn_Bateria.setObjectName("Rbtn_Bateria")
        self.frame_11 = QtWidgets.QFrame(self.tab_3)
        self.frame_11.setGeometry(QtCore.QRect(10, 220, 436, 91))
        tam=self.frame_11.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.frame_11.setGeometry(QtCore.QRect(*esc))
        radio = 8 / 112.5222328226425 * dpi
        self.frame_11.setStyleSheet("background-color: rgb(255, 231, 215);\n"
f"border-radius: {radio}px;")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.BtnParar_Corto = BotonIluminado(self.frame_11)
        self.BtnParar_Corto.setGeometry(QtCore.QRect(290, 40, 75, 26))
        tam=self.BtnParar_Corto.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnParar_Corto.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnParar_Corto.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnParar_Corto.setObjectName("BtnParar_Corto")
        self.BtnIniciar_Corto = BotonIluminado(self.frame_11)
        self.BtnIniciar_Corto.setGeometry(QtCore.QRect(290, 40, 75, 26))
        tam=self.BtnIniciar_Corto.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.BtnIniciar_Corto.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.BtnIniciar_Corto.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.BtnIniciar_Corto.setObjectName("BtnIniciar_Corto")
        self.label_65 = QtWidgets.QLabel(self.frame_11)
        self.label_65.setGeometry(QtCore.QRect(0, 0, 436, 20))
        tam=self.label_65.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_65.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.label_64 = QtWidgets.QLabel(self.frame_11)
        self.label_64.setGeometry(QtCore.QRect(60, 40, 35, 22))
        tam=self.label_64.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_64.setGeometry(QtCore.QRect(*esc))
        self.label_64.setObjectName("label_64")
        self.Cmb_ModoCorto = QtWidgets.QComboBox(self.frame_11)
        self.Cmb_ModoCorto.setGeometry(QtCore.QRect(100, 40, 69, 22))
        tam=self.Cmb_ModoCorto.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Cmb_ModoCorto.setGeometry(QtCore.QRect(*esc))
        radio = 4 / 112.5222328226425 * dpi
        borde = 1 / 112.5222328226425 * dpi
        self.Cmb_ModoCorto.setStyleSheet("color: black;\n"
"background-color: rgb(251, 252, 252);\n"
f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;")
        self.Cmb_ModoCorto.setEditable(False)
        self.Cmb_ModoCorto.setObjectName("Cmb_ModoCorto")
        self.Cmb_ModoCorto.addItem("")
        self.Cmb_ModoCorto.addItem("")
        self.Cmb_ModoCorto.addItem("")
        self.Cmb_ModoCorto.addItem("")
        self.tabWidget.addTab(self.tab_3, "")
        self.LblConectado = QtWidgets.QLabel(self.centralwidget)
        self.LblConectado.setGeometry(QtCore.QRect(67, 70, 26, 26))
        tam=self.LblConectado.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblConectado.setGeometry(QtCore.QRect(*esc))
        radio = 12 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.LblConectado.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove green;\n"
"border-style: outset;\n"
"background-color: rgb(0, 236, 0);")
        self.LblConectado.setText("")
        self.LblConectado.setObjectName("LblConectado")
        self.LblDesconectado = QtWidgets.QLabel(self.centralwidget)
        self.LblDesconectado.setGeometry(QtCore.QRect(67, 70, 26, 26))
        tam=self.LblDesconectado.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblDesconectado.setGeometry(QtCore.QRect(*esc))
        radio = 12 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.LblDesconectado.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;\n"
"background-color: rgb(203, 203, 203);")
        self.LblDesconectado.setText("")
        self.LblDesconectado.setObjectName("LblDesconectado")
        self.LblApagado = QtWidgets.QLabel(self.centralwidget)
        self.LblApagado.setGeometry(QtCore.QRect(180, 70, 26, 26))
        tam=self.LblApagado.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblApagado.setGeometry(QtCore.QRect(*esc))
        radio = 12 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.LblApagado.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"border-style: outset;\n"
"background-color: rgb(203, 203, 203);")
        self.LblApagado.setText("")
        self.LblApagado.setObjectName("LblApagado")
        self.LblEncendido = QtWidgets.QLabel(self.centralwidget)
        self.LblEncendido.setGeometry(QtCore.QRect(180, 70, 26, 26))
        tam=self.LblEncendido.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblEncendido.setGeometry(QtCore.QRect(*esc))
        radio = 12 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.LblEncendido.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove green;\n"
"border-style: outset;\n"
"background-color: rgb(0, 236, 0);")
        self.LblEncendido.setText("")
        self.LblEncendido.setObjectName("LblEncendido")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(270, 40, 48, 16))
        tam=self.label_23.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_23.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(459, 40, 60, 16))
        tam=self.label_24.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_24.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(610, 40, 80, 16))
        tam=self.label_25.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_25.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(776, 40, 70, 16))
        tam=self.label_26.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_26.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.LblModoOP = QtWidgets.QLabel(self.centralwidget)
        self.LblModoOP.setGeometry(QtCore.QRect(270, 70, 48, 26))
        tam=self.LblModoOP.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblModoOP.setGeometry(QtCore.QRect(*esc))
        self.LblModoOP.setText("")
        self.LblModoOP.setAlignment(QtCore.Qt.AlignCenter)
        self.LblModoOP.setObjectName("LblModoOP")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(519, 72, 21, 22))
        tam=self.label_28.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_28.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(680, 72, 21, 22))
        tam=self.label_29.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_29.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(841, 72, 21, 22))
        tam=self.label_30.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_30.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.Txt_LeeVolt = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_LeeVolt.setEnabled(False)
        self.Txt_LeeVolt.setGeometry(QtCore.QRect(459, 70, 60, 26))
        tam=self.Txt_LeeVolt.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_LeeVolt.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_LeeVolt.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);\n"
"")
        self.Txt_LeeVolt.setObjectName("Txt_LeeVolt")
        self.Txt_LeeCorr = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_LeeCorr.setEnabled(False)
        self.Txt_LeeCorr.setGeometry(QtCore.QRect(620, 70, 60, 26))
        tam=self.Txt_LeeCorr.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_LeeCorr.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_LeeCorr.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);\n"
"")
        self.Txt_LeeCorr.setObjectName("Txt_LeeCorr")
        self.Txt_LeePot = QtWidgets.QTextEdit(self.centralwidget)
        self.Txt_LeePot.setEnabled(False)
        self.Txt_LeePot.setGeometry(QtCore.QRect(781, 70, 60, 26))
        tam=self.Txt_LeePot.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.Txt_LeePot.setGeometry(QtCore.QRect(*esc))
        radio = 6 / 112.5222328226425 * dpi
        borde = 2 / 112.5222328226425 * dpi
        self.Txt_LeePot.setStyleSheet(f"border-radius: {radio}px; border: {borde}px groove gray;\n"
"background-color: rgb(251, 252, 252);\n"
"")
        self.Txt_LeePot.setObjectName("Txt_LeePot")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(40, 40, 80, 16))
        tam=self.label_27.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_27.setGeometry(QtCore.QRect(*esc))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(150, 40, 86, 16))
        tam=self.label_31.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_31.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.LblFuncion = QtWidgets.QLabel(self.centralwidget)
        self.LblFuncion.setGeometry(QtCore.QRect(360, 70, 48, 26))
        tam=self.LblFuncion.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.LblFuncion.setGeometry(QtCore.QRect(*esc))
        self.LblFuncion.setText("")
        self.LblFuncion.setAlignment(QtCore.Qt.AlignCenter)
        self.LblFuncion.setObjectName("LblFuncion")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(350, 40, 65, 16))
        tam=self.label_32.geometry().getRect()
        esc=[int(el/112.5222328226425*dpi) for el in tam]
        self.label_32.setGeometry(QtCore.QRect(*esc))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.LblEncendido.raise_()
        self.LblApagado.raise_()
        self.tabWidget.raise_()
        self.LblConectado.raise_()
        self.LblDesconectado.raise_()
        self.label_23.raise_()
        self.label_24.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.LblModoOP.raise_()
        self.label_28.raise_()
        self.label_29.raise_()
        self.label_30.raise_()
        self.Txt_LeeVolt.raise_()
        self.Txt_LeeCorr.raise_()
        self.Txt_LeePot.raise_()
        self.label_27.raise_()
        self.label_31.raise_()
        self.LblFuncion.raise_()
        self.label_32.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionConectar = QtWidgets.QAction(MainWindow)
        self.actionConectar.setObjectName("actionConectar")
        self.actionDesconectar = QtWidgets.QAction(MainWindow)
        self.actionDesconectar.setObjectName("actionDesconectar")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionConectar_2 = QtWidgets.QAction(MainWindow)
        self.actionConectar_2.setObjectName("actionConectar_2")
        self.actionDesconectar_2 = QtWidgets.QAction(MainWindow)
        self.actionDesconectar_2.setObjectName("actionDesconectar_2")
        self.actionEncender_carga = QtWidgets.QAction(MainWindow)
        self.actionEncender_carga.setCheckable(False)
        self.actionEncender_carga.setObjectName("actionEncender_carga")
        self.actionApagar_carga = QtWidgets.QAction(MainWindow)
        self.actionApagar_carga.setObjectName("actionApagar_carga")
        self.actionEncender_carga_2 = QtWidgets.QAction(MainWindow)
        self.actionEncender_carga_2.setObjectName("actionEncender_carga_2")
        self.actionApagar_carga_2 = QtWidgets.QAction(MainWindow)
        self.actionApagar_carga_2.setObjectName("actionApagar_carga_2")
        self.actionConectar_3 = QtWidgets.QAction(MainWindow)
        self.actionConectar_3.setObjectName("actionConectar_3")
        self.actionDesconectar_3 = QtWidgets.QAction(MainWindow)
        self.actionDesconectar_3.setObjectName("actionDesconectar_3")
        self.actionSalir_2 = QtWidgets.QAction(MainWindow)
        self.actionSalir_2.setObjectName("actionSalir_2")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.BtnEstablecerMax, self.BtnEstablecerValMod)
        MainWindow.setTabOrder(self.BtnEstablecerValMod, self.Rbtn_MCR)
        MainWindow.setTabOrder(self.Rbtn_MCR, self.BtnParar_PBateria)
        MainWindow.setTabOrder(self.BtnParar_PBateria, self.BtnEstablecer_OpLista)
        MainWindow.setTabOrder(self.BtnEstablecer_OpLista, self.Rbtn_MCV)
        MainWindow.setTabOrder(self.Rbtn_MCV, self.BtnIniciar_Lista)
        MainWindow.setTabOrder(self.BtnIniciar_Lista, self.Rbtn_MCW)
        MainWindow.setTabOrder(self.Rbtn_MCW, self.BtnDesconectar)
        MainWindow.setTabOrder(self.BtnDesconectar, self.BtnApagar)
        MainWindow.setTabOrder(self.BtnApagar, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.CmbPuerto)
        MainWindow.setTabOrder(self.CmbPuerto, self.Cmb_ModoLista)
        MainWindow.setTabOrder(self.Cmb_ModoLista, self.Rbtn_Unavez)
        MainWindow.setTabOrder(self.Rbtn_Unavez, self.Rbtn_Repetir)
        MainWindow.setTabOrder(self.Rbtn_Repetir, self.BtnEncender)
        MainWindow.setTabOrder(self.BtnEncender, self.BtnParar_Lista)
        MainWindow.setTabOrder(self.BtnParar_Lista, self.Rbtn_MCC)
        MainWindow.setTabOrder(self.Rbtn_MCC, self.BtnIniciar_PBateria)
        MainWindow.setTabOrder(self.BtnIniciar_PBateria, self.CmbBaudrate)
        MainWindow.setTabOrder(self.CmbBaudrate, self.BtnConectar)
        MainWindow.setTabOrder(self.BtnConectar, self.Rbtn_Fijo)
        MainWindow.setTabOrder(self.Rbtn_Fijo, self.Rbtn_Corto)
        MainWindow.setTabOrder(self.Rbtn_Corto, self.Rbtn_Lista)
        MainWindow.setTabOrder(self.Rbtn_Lista, self.Rbtn_Bateria)
        MainWindow.setTabOrder(self.Rbtn_Bateria, self.BtnParar_Corto)
        MainWindow.setTabOrder(self.BtnParar_Corto, self.BtnIniciar_Corto)
        MainWindow.setTabOrder(self.BtnIniciar_Corto, self.Cmb_ModoCorto)
        MainWindow.setTabOrder(self.Cmb_ModoCorto, self.Txt_LeeVolt)
        MainWindow.setTabOrder(self.Txt_LeeVolt, self.Txt_LeeCorr)
        MainWindow.setTabOrder(self.Txt_LeeCorr, self.Txt_LeePot)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Carga electrónica BK Presicion 85XX - ITM"))
        self.label.setText(_translate("MainWindow", "Comunicación serial"))
        self.label_2.setText(_translate("MainWindow", "Puerto"))
        self.label_3.setText(_translate("MainWindow", "Baudrate"))
        self.CmbBaudrate.setItemText(0, _translate("MainWindow", "38400"))
        self.CmbBaudrate.setItemText(1, _translate("MainWindow", "4800"))
        self.CmbBaudrate.setItemText(2, _translate("MainWindow", "9600"))
        self.CmbBaudrate.setItemText(3, _translate("MainWindow", "19200"))
        self.BtnConectar.setText(_translate("MainWindow", "Conectar"))
        self.BtnDesconectar.setText(_translate("MainWindow", "Desconectar"))
        self.label_10.setText(_translate("MainWindow", "Configuración del instrumento"))
        self.label_11.setText(_translate("MainWindow", "Límite de voltaje:"))
        self.label_12.setText(_translate("MainWindow", "Límite de corriente:"))
        self.BtnEstablecerMax.setText(_translate("MainWindow", "Establecer"))
        self.label_13.setText(_translate("MainWindow", "Límite de potencia: "))
        self.label_14.setText(_translate("MainWindow", "V"))
        self.label_15.setText(_translate("MainWindow", "A"))
        self.label_16.setText(_translate("MainWindow", "W"))
        self.label_4.setText(_translate("MainWindow", "Información de la carga electrónica"))
        self.label_6.setText(_translate("MainWindow", "Rangos máximos absolutos"))
        self.label_5.setText(_translate("MainWindow", "Modelo"))
        self.label_17.setText(_translate("MainWindow", "W,"))
        self.label_18.setText(_translate("MainWindow", "V,"))
        self.label_19.setText(_translate("MainWindow", "A"))
        self.label_35.setText(_translate("MainWindow", "Modo de operación"))
        self.Rbtn_MCC.setText(_translate("MainWindow", "CC"))
        self.Rbtn_MCV.setText(_translate("MainWindow", "CV"))
        self.Rbtn_MCW.setText(_translate("MainWindow", "CW"))
        self.Rbtn_MCR.setText(_translate("MainWindow", "CR"))
        self.label_9.setText(_translate("MainWindow", "Por favor seleccione el modo de operación con el que desea trabajar"))
        self.label_36.setText(_translate("MainWindow", "Valor según modo de operación"))
        self.label_37.setText(_translate("MainWindow", "Voltaje CV:"))
        self.label_38.setText(_translate("MainWindow", "Corriente CC:"))
        self.BtnEstablecerValMod.setText(_translate("MainWindow", "Establecer"))
        self.label_39.setText(_translate("MainWindow", "Potencia CW: "))
        self.label_40.setText(_translate("MainWindow", "V"))
        self.label_41.setText(_translate("MainWindow", "A"))
        self.label_42.setText(_translate("MainWindow", "W"))
        self.label_43.setText(_translate("MainWindow", "Ω"))
        self.label_44.setText(_translate("MainWindow", "Resistencia  CR:"))
        self.label_34.setText(_translate("MainWindow", "Encender/Apagar carga electrónica"))
        self.BtnApagar.setText(_translate("MainWindow", "Apagar"))
        self.BtnEncender.setText(_translate("MainWindow", "Encender"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Configuración"))
        self.label_54.setText(_translate("MainWindow", "Operación de lista"))
        self.label_58.setText(_translate("MainWindow", "Valor min"))
        self.label_59.setText(_translate("MainWindow", "Valor max"))
        self.label_61.setText(_translate("MainWindow", "Tiempo"))
        self.BtnEstablecer_OpLista.setText(_translate("MainWindow", "Configurar"))
        self.label_49.setText(_translate("MainWindow", "Modo"))
        self.Cmb_ModoLista.setCurrentText(_translate("MainWindow", "CC"))
        self.Cmb_ModoLista.setItemText(0, _translate("MainWindow", "CC"))
        self.Cmb_ModoLista.setItemText(1, _translate("MainWindow", "CV"))
        self.Cmb_ModoLista.setItemText(2, _translate("MainWindow", "CW"))
        self.Cmb_ModoLista.setItemText(3, _translate("MainWindow", "CR"))
        self.label_51.setText(_translate("MainWindow", "# de pasos"))
        self.Rbtn_Unavez.setText(_translate("MainWindow", "Una vez"))
        self.Rbtn_Repetir.setText(_translate("MainWindow", "Repetir"))
        self.label_56.setText(_translate("MainWindow", "Si desea realizar barridos por favor seleccione el modo lista, el número máximo de pasos es de 1000"))
        self.BtnIniciar_Lista.setText(_translate("MainWindow", "Iniciar"))
        self.BtnParar_Lista.setText(_translate("MainWindow", "Parar"))
        self.LblPotmin.setText(_translate("MainWindow", "W"))
        self.LblVmin.setText(_translate("MainWindow", "V"))
        self.LblOhmmax.setText(_translate("MainWindow", "Ω"))
        self.LblVmax.setText(_translate("MainWindow", "V"))
        self.label_68.setText(_translate("MainWindow", "s"))
        self.LblCmin.setText(_translate("MainWindow", "A"))
        self.LblCmax.setText(_translate("MainWindow", "A"))
        self.LblPotmax.setText(_translate("MainWindow", "W"))
        self.LblOhmmin.setText(_translate("MainWindow", "Ω"))
        self.BtnParar_PBateria.setText(_translate("MainWindow", "Parar"))
        self.label_46.setText(_translate("MainWindow", "Voltaje min"))
        self.BtnIniciar_PBateria.setText(_translate("MainWindow", "Iniciar"))
        self.label_45.setText(_translate("MainWindow", "Corriente CC:"))
        self.label_55.setText(_translate("MainWindow", "Prueba de batería"))
        self.label_47.setText(_translate("MainWindow", "Capacidad:"))
        self.label_62.setText(_translate("MainWindow", "Ah"))
        self.label_63.setText(_translate("MainWindow", "Wh"))
        self.label_50.setText(_translate("MainWindow", "Función de trabajo"))
        self.Rbtn_Fijo.setText(_translate("MainWindow", "Fijo"))
        self.Rbtn_Corto.setText(_translate("MainWindow", "Simulación de corto"))
        self.Rbtn_Lista.setText(_translate("MainWindow", "Lista"))
        self.Rbtn_Bateria.setText(_translate("MainWindow", "Prueba de batería"))
        self.BtnParar_Corto.setText(_translate("MainWindow", "Parar"))
        self.BtnIniciar_Corto.setText(_translate("MainWindow", "Iniciar"))
        self.label_65.setText(_translate("MainWindow", "Simulación de corto"))
        self.label_64.setText(_translate("MainWindow", "Modo"))
        self.Cmb_ModoCorto.setCurrentText(_translate("MainWindow", "CC"))
        self.Cmb_ModoCorto.setItemText(0, _translate("MainWindow", "CC"))
        self.Cmb_ModoCorto.setItemText(1, _translate("MainWindow", "CV"))
        self.Cmb_ModoCorto.setItemText(2, _translate("MainWindow", "CW"))
        self.Cmb_ModoCorto.setItemText(3, _translate("MainWindow", "CR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Modos de operación"))
        self.label_23.setText(_translate("MainWindow", "Modo"))
        self.label_24.setText(_translate("MainWindow", "Voltaje"))
        self.label_25.setText(_translate("MainWindow", "Corriente"))
        self.label_26.setText(_translate("MainWindow", "Potencia"))
        self.label_28.setText(_translate("MainWindow", "V"))
        self.label_29.setText(_translate("MainWindow", "A"))
        self.label_30.setText(_translate("MainWindow", "W"))
        self.label_27.setText(_translate("MainWindow", "Conexión"))
        self.label_31.setText(_translate("MainWindow", "Encendido"))
        self.label_32.setText(_translate("MainWindow", "Función"))
        self.actionConectar.setText(_translate("MainWindow", "Conectar"))
        self.actionDesconectar.setText(_translate("MainWindow", "Desconectar"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionConectar_2.setText(_translate("MainWindow", "Conectar"))
        self.actionDesconectar_2.setText(_translate("MainWindow", "Desconectar"))
        self.actionEncender_carga.setText(_translate("MainWindow", "Encender carga"))
        self.actionApagar_carga.setText(_translate("MainWindow", "Apagar carga"))
        self.actionEncender_carga_2.setText(_translate("MainWindow", "Encender carga"))
        self.actionApagar_carga_2.setText(_translate("MainWindow", "Apagar carga"))
        self.actionConectar_3.setText(_translate("MainWindow", "Conectar"))
        self.actionDesconectar_3.setText(_translate("MainWindow", "Desconectar"))
        self.actionSalir_2.setText(_translate("MainWindow", "Salir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
