# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ventana_advertencia.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Advertencia(object):
    def setupUi(self, Advertencia):
        Advertencia.setObjectName("Advertencia")
        Advertencia.resize(270, 80)
        Advertencia.setMaximumSize(QtCore.QSize(270, 80))
        Advertencia.setStyleSheet("background-color: rgb(255, 245, 226);")
        self.centralwidget = QtWidgets.QWidget(Advertencia)
        self.centralwidget.setObjectName("centralwidget")
        self.LblAdvertencia = QtWidgets.QLabel(self.centralwidget)
        self.LblAdvertencia.setGeometry(QtCore.QRect(10, 10, 250, 50))
        self.LblAdvertencia.setAlignment(QtCore.Qt.AlignCenter)
        self.LblAdvertencia.setObjectName("LblAdvertencia")
        Advertencia.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Advertencia)
        self.statusbar.setObjectName("statusbar")
        Advertencia.setStatusBar(self.statusbar)

        self.retranslateUi(Advertencia)
        QtCore.QMetaObject.connectSlotsByName(Advertencia)

    def retranslateUi(self, Advertencia):
        _translate = QtCore.QCoreApplication.translate
        Advertencia.setWindowTitle(_translate("Advertencia", "Cargando..."))
        self.LblAdvertencia.setText(_translate("Advertencia", "Buscando puertos COM..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Advertencia = QtWidgets.QMainWindow()
    ui = Ui_Advertencia()
    ui.setupUi(Advertencia)
    Advertencia.show()
    sys.exit(app.exec_())
